init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
    - /^release\/.*/
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\build.ps1 -ci
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017
